# -*- coding: utf-8 -*-
"""ass13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110cd6u2MWiQsmi1WruPuLvDzTonaayv1
"""

from flask import Flask, request, jsonify
import pickle
import numpy as np

app = Flask(__name__)

# Load your trained model
model = pickle.load(open('credit_card_spam_model.pkl', 'rb'))

@app.route('/')
def home():
    return "Credit Card Spam Detection API"

@app.route('/predict', methods=['POST'])
def predict():
    # Assuming the incoming request will have JSON data
    data = request.json
    features = np.array(data['features']).reshape(1, -1)  # reshape the data as required

    # Predict the output using the loaded model
    prediction = model.predict(features)
    result = {'prediction': int(prediction[0])}

    return jsonify(result)

if __name__ == "__main__":
    app.run(debug=True)